What is numpy?

Numpy is a fundamental package for scientific computing in Python.

In [4]:
# creating a NumPy array

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [6]:
# 2D and 3D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
np.array([1, 2, 0], dtype=complex)

array([1.+0.j, 2.+0.j, 0.+0.j])

In [18]:
# np.arange

a = np.arange(1, 11, 2)
print(a)
for i in a:
    print(i)

[1 3 5 7 9]
1
3
5
7
9


In [26]:
# with reshape

np.arange(1, 13).reshape(6, 2)  # reshape makes an array in multidimentional

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
# np.ones and np.zeros

np.ones((3, 4))
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.random.random((3, 2))

array([[0.48637945, 0.39680876],
       [0.18128688, 0.78525501],
       [0.74973838, 0.05643735]])

In [ ]:
# np.linspace (linear space)

np.linspace(-10, 10, 5)  # (lowerRange , UpperRange , total items) and linerly seperatable points generate 


array([-10.,  -5.,   0.,   5.,  10.])

In [70]:
# np.identity

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])