In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 100, 15)
np.sort(a)[::-1]

array([95, 93, 87, 77, 67, 63, 50, 43, 43, 37, 34, 34, 25, 12,  3],
      dtype=int32)

In [3]:
b = np.random.randint(1, 100, 15).reshape(5, 3)
np.sort(b, axis=0)  # 0 => col by sort , 1 => row by sort
np.sort(b, axis=1)  # 0 => col by sort , 1 => row by sort

array([[24, 34, 62],
       [39, 46, 89],
       [42, 51, 89],
       [22, 29, 84],
       [19, 68, 87]], dtype=int32)

np.append

In [4]:
a
np.append(a, 200)

array([ 34,   3,  93,  63,  67,  25,  37,  43,  95,  50,  34,  12,  77,
        43,  87, 200])

In [40]:
np.append(b, np.random.randint(1, 100, (b.shape[0], 1)), axis=1)

array([[62, 24, 34,  8],
       [89, 46, 39, 22],
       [51, 89, 42, 70],
       [29, 22, 84, 52],
       [68, 19, 87, 69]], dtype=int32)

In [6]:
np.append(b, np.random.randint(1, 100, (2, b.shape[1])), axis=0)

array([[62, 24, 34],
       [89, 46, 39],
       [51, 89, 42],
       [29, 22, 84],
       [68, 19, 87],
       [85, 37, 69],
       [71, 62,  3]], dtype=int32)

np.concatenate

In [168]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [171]:
np.concatenate((c, d), axis=1)
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique

In [173]:
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

mp.expand_dims

In [176]:
np.expand_dims(a, axis=0)

array([[61, 10, 73, 54, 21, 57, 23, 78,  4, 49, 53, 62, 95, 32,  3]],
      dtype=int32)

In [177]:
np.expand_dims(a, axis=1)

array([[61],
       [10],
       [73],
       [54],
       [21],
       [57],
       [23],
       [78],
       [ 4],
       [49],
       [53],
       [62],
       [95],
       [32],
       [ 3]], dtype=int32)

np.where

The function returns the indices of element 

In [204]:
a

array([ 0, 10,  0,  0, 21,  0, 23,  0,  4, 49,  0,  0,  0, 32,  3],
      dtype=int32)

In [183]:
np.where(a > 50)

(array([ 0,  2,  3,  5,  7, 10, 11, 12]),)

In [185]:
# replace all values > 50 with 0
# np.where(condition , true , false)
np.where(a > 50, 0, a)
# a[np.where(a > 50)] = 0

array([ 0, 10,  0,  0, 21,  0, 23,  0,  4, 49,  0,  0,  0, 32,  3],
      dtype=int32)

In [186]:
# replace all even number with 0
np.where(a % 2 == 0, 0, a)

array([ 0,  0,  0,  0, 21,  0, 23,  0,  0, 49,  0,  0,  0,  0,  3],
      dtype=int32)

np.argmax

In [189]:
np.argmax(a)

np.int64(9)

In [199]:
print(b)
np.argmax(b, axis=1)  # 0 => col and 1=> row

[[66 16 54]
 [ 9 73 58]
 [84 68 67]
 [64 16 65]
 [79 60 58]]


array([0, 1, 0, 2, 0])

In [235]:
# argmin
a = np.random.randint(1, 100, 50)
print(a)
np.argmin(a)

[29 83 29 40 40 70 29 94 96 27 40 92 13 34 21 67 12 22 38  1 30 98 66 93
 68 60 53 46 37 12  9 53 74 92 48 26 40  2 17  7 91 58 72 96 70 75 61 20
  1 26]


np.int64(19)

In [248]:
print(b)
print(np.argmin(b, axis=0))
np.argmin(b, axis=1)

[[66 16 54]
 [ 9 73 58]
 [84 68 67]
 [64 16 65]
 [79 60 58]]
[1 0 0]


array([1, 0, 2, 1, 2])

np.cumsum

In [263]:
print(b)
np.cumsum(b, axis=0)  # 0=> means it sum in the column and 1 => means it sum in the row

[[66 16 54]
 [ 9 73 58]
 [84 68 67]
 [64 16 65]
 [79 60 58]]


array([[ 66,  16,  54],
       [ 75,  89, 112],
       [159, 157, 179],
       [223, 173, 244],
       [302, 233, 302]])

In [266]:
np.cumsum(a)

array([  29,  112,  141,  181,  221,  291,  320,  414,  510,  537,  577,
        669,  682,  716,  737,  804,  816,  838,  876,  877,  907, 1005,
       1071, 1164, 1232, 1292, 1345, 1391, 1428, 1440, 1449, 1502, 1576,
       1668, 1716, 1742, 1782, 1784, 1801, 1808, 1899, 1957, 2029, 2125,
       2195, 2270, 2331, 2351, 2352, 2378])

In [270]:
# np.cumprod

np.cumprod(a)

array([                  29,                 2407,                69803,
                    2792120,            111684800,           7817936000,
               226720144000,       21311693536000,     2045922579456000,
          55239909645312000,  2209596385812480000,   368682683943092224,
        4792874891260198912, -3062950360539201536, -8981725350194577408,
        6966955969378516992, -8630248736005554176, -5398031455026675712,
       -2211010480208609280, -2211010480208609280,  7456661888579928064,
       -7116897867549114368, -8546657415502757888, -1629144472245764096,
        -101359670454648832, -6081580227278929920, -8729102792720908288,
        4289641156448354304, -7303973874796855296,  4586033870985494528,
        4380816691450347520, -7624388311355752448,  7644331244670418944,
        2302199708715581440,  -174878423909400576, -4546839021644414976,
        2593879871318917120,  5187759742637834240, -4041804743704576000,
        8600854941487071232,  7914548579522314240, 

np.percentile

In [ ]:
print(a)
# print(np.sum(a) * 0.1)
np.percentile(a, 50)

[29 83 29 40 40 70 29 94 96 27 40 92 13 34 21 67 12 22 38  1 30 98 66 93
 68 60 53 46 37 12  9 53 74 92 48 26 40  2 17  7 91 58 72 96 70 75 61 20
  1 26]


np.float64(40.0)

In [282]:
np.median(a)

np.float64(40.0)

np.histogram

In [14]:
a = np.random.randint(1, 100, 50)

In [16]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([7, 3, 3, 8, 4, 6, 3, 7, 5, 4]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

 np.corrcoef

In [17]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

In [19]:
item = [10, 20, 30, 40, 50, 60, 70, 80]
a[np.isin(a, item)]

array([20, 70, 60, 30, 50], dtype=int32)

np.filip

In [25]:
print(b)
np.flip(b, axis=1)

[[62 24 34]
 [89 46 39]
 [51 89 42]
 [29 22 84]
 [68 19 87]]


array([[34, 24, 62],
       [39, 46, 89],
       [42, 89, 51],
       [84, 22, 29],
       [87, 19, 68]], dtype=int32)

np.put

In [ ]:
np.put(a, [0, 1], [110, 530]) # you can change multiple item in a array

In [29]:
a

array([110, 530,  20,  54,   5,  44,  89,  55,  33,  21,  79,  34,  84,
        77,  44,  83,  99,   4,  34,   3,  41,  55,  93,  75,  93,  70,
        18,  60,  76,   2,  88,  76,  88,   3,  69,  14,  36,  95,  52,
        56,  48,   5,  78,  30,   8,  69,  50,  32,  19,  33], dtype=int32)

In [31]:
np.delete(a, [0, 1])

array([20, 54,  5, 44, 89, 55, 33, 21, 79, 34, 84, 77, 44, 83, 99,  4, 34,
        3, 41, 55, 93, 75, 93, 70, 18, 60, 76,  2, 88, 76, 88,  3, 69, 14,
       36, 95, 52, 56, 48,  5, 78, 30,  8, 69, 50, 32, 19, 33],
      dtype=int32)