What is numpy?

Numpy is a fundamental package for scientific computing in Python.

In [4]:
# creating a NumPy array

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [6]:
# 2D and 3D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
np.array([1, 2, 0], dtype=complex)

array([1.+0.j, 2.+0.j, 0.+0.j])

In [18]:
# np.arange

a = np.arange(1, 11, 2)
print(a)
for i in a:
    print(i)

[1 3 5 7 9]
1
3
5
7
9


In [26]:
# with reshape

np.arange(1, 13).reshape(6, 2)  # reshape makes an array in multidimentional

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
# np.ones and np.zeros

np.ones((3, 4))
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.random.random((3, 2))

array([[0.48637945, 0.39680876],
       [0.18128688, 0.78525501],
       [0.74973838, 0.05643735]])

In [ ]:
# np.linspace (linear space)

np.linspace(-10, 10, 5)  # (lowerRange , UpperRange , total items) and linerly seperatable points generate 


array([-10.,  -5.,   0.,   5.,  10.])

In [70]:
# np.identity

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
a1 = np.arange(1, 11)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Array attributes

In [85]:
# ndim (number of dimensions)
a3.ndim

3

In [86]:
# shape (this dimension has how many items)

a1.shape
a2.shape
# a3.shape

(3, 4)

In [89]:
# size

a2.size
a3.size

8

In [ ]:
# item size (this item how many size in the memory)
a3.itemsize # by default this is 64 bits

8

In [98]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
complex128


# changing DataTypes

In [106]:
# astype ( for converting data types for memory size reduces)
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array operations



In [111]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

# Scalar operations

# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [115]:
# relational operators

a1 != 5

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [119]:
# vector operations
# arithmetic

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# array functions

In [177]:
a1 = np.random.random((3, 3))
a1 = np.round(a1 * 100)
a1

array([[71., 40., 85.],
       [ 8., 40., 75.],
       [47.,  0., 63.]])

In [170]:
# max/min/sum/prod
np.max(a1)

np.min(a1)

np.sum(a1)

# print(np.prod(a1))

np.max(a1, axis=0)  # 0-> column
np.max(a1, axis=1)  # 1-> row

array([70., 68., 89.])

In [180]:
# mean/median/std/var
np.mean(a1, axis=0)
np.median(a1, axis=1)
np.std(a1, axis=1)
np.var(a1, axis=1)

array([353.55555556, 748.66666667, 714.88888889])

In [182]:
# trignometric function

np.sin(a1)
np.cos(a1)
np.tan(a1)

array([[-3.0776204 , -1.11721493,  0.17887017],
       [-6.79971146, -1.11721493, -0.42070095],
       [-0.12452757,  0.        ,  0.16974975]])

In [188]:
# dot product
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(4, 3)

np.dot(a1, a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [192]:
# log and exponents

np.exp(a1)
np.log(a1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8048\3234091191.py:4: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [195]:
# round/floor/cel
np.round(a1)
np.floor(a1)
np.ceil(a1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# indexing and slicing